*HELLO* ï¾ 
*â•­â”€ã€Œ á´„á´á´á´á´€É´á´…êœ± á´˜á´€É´á´‡ÊŸã€*
*â”‚â—ˆ ğšğ™°ğ™¼ ğš„ğš‚ğ™°ğ™¶ğ™´ -* 99.04MB / 63276MB
*â”‚â—ˆ ğšğš„ğ™½ğšƒğ™¸ğ™¼ğ™´ -* 5 hours, 50 minutes, 10 seconds
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚âšœï¸ OWNER Command List:*
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* update
*â”‚Use:* .updatet
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* fetch
*â”‚Use:* undefined
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* rename
*â”‚Use:* .rename < Jid address >
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* sendactivejid
*â”‚Use:* .sendactivejid 
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* forward2
*â”‚Use:* .forward2 < Jid address 1, Jid address 2, ...>
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* forward
*â”‚Use:* .forward < Jid address >
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* admin
*â”‚Use:* .admin <quote|reply|number>
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* boom
*â”‚Use:* .boom <jid> & <count>
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* shutdown
*â”‚Use:* .shutdown
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* broadcast
*â”‚Use:* .broadcast
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* getpp
*â”‚Use:* .getpp
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* setpp
*â”‚Use:* .setpp
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* block
*â”‚Use:* .block
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* unblock
*â”‚Use:* .unblock
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* clearchats
*â”‚Use:* .clearchats
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* restart
*â”‚Use:* .restart
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* setfullpp
*â”‚Use:* .setfullpp *<repllied photo>*
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* evl
*â”‚Use:* .ev
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* csong
*â”‚Use:* .csong < Text or Link & channeljid >
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* activemv
*â”‚Use:* .activemv *<jid address/quoted jid>*
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* deactivemv
*â”‚Use:* .deactivemv *<jid address/quoted jid>*
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* ban
*â”‚Use:* .ban *<jid address/quoted jid>*
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* unban
*â”‚Use:* .unban *<jid address/quoted jid>*
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* apply
*â”‚Use:* .apply <Text>
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* setting
*â”‚Use:* .settings
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*

*â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*
*â”‚Command:* resetdb
*â”‚Use:* .resetdb
*â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â—â—â–º*


â  *Total Commands in OWNER*: 26


*Github Repo:* https://github.com/sahanxpasi-MD/RIO_Bypass-MD

 *ã‹› ğ™¿ğ™¾ğš†ğ™´ğšğ™³ ğ™±ğšˆ ğ™°ğš‚ğ™¸ğšƒğ™·ğ™°  ã€½ï¸ï¼¤*
